### ISSUE TITLE
РК №1

### ISSUE THREAD

**Issue by StealthTech** [frontend-park-mail-ru/2023_2_Rabotyagi#13]
- [x] Не работает авторизация (не через cookies)
- [x] Не работает регистрация (не через cookies)
- [x] Код не был запушен в main
- [x] Нет ссылки на сайт в README.md
- [x] Видно техническую кнопку вместо лого в шапке на регистрации
- [x] Валидация формы показывает ошибки через alert
- [x] Картинки в списке объявлений берутся со стороннего сайта
- [x] Добавить sans-serif фолбек на шрифты и починить импорт (унести с google fonts)
- [x] Денег больше ожидаемого
<img width="94" alt="image" src="https://github.com/frontend-park-mail-ru/2023_2_Rabotyagi/assets/5190765/07f2c34c-e898-4188-b5b9-4af759d0c58d">

- [x] Отдельный скролл на списке не нужен — приводит к тому, что обрезается контент

**Comment by NickDemiman** [comment]
> * [x]  Не работает авторизация (не через cookies)
> * [x]  Не работает регистрация (не через cookies)
> * [x]  Код не был запушен в main
> * [x]  Нет ссылки на сайт в README.md
> * [x]  Видно техническую кнопку вместо лого в шапке на регистрации
> * [x]  Валидация формы показывает ошибки через alert
> * [x]  Картинки в списке объявлений берутся со стороннего сайта
> * [x]  Добавить sans-serif фолбек на шрифты и починить импорт (унести с google fonts)
> * [x]  Денег больше ожидаемого
> 
> <img alt="image" width="94" src="https://user-images.githubusercontent.com/5190765/273260806-07f2c34c-e898-4188-b5b9-4af759d0c58d.png">
> * [x]  Отдельный скролл на списке не нужен — приводит к тому, что обрезается контент

Пингую

**Comment by GreatFix** [comment]
@StealthTech привет, проверишь ребят ?

**Comment by NickDemiman** [comment]
@StealthTech а ты с мок сервером тестировать будешь или нам на прод надо выкатывать?

**Comment by NickDemiman** [comment]
я сделал ротацию картинок и в статику запихнул, правда, опять же. это все мок сервак у меня реализует

**Comment by StealthTech** [comment]
Нужно выкатывать на прод. Картинки нужно залить нормально, они должны быть не на фронте, а храниться на беке. Mock сервер это хорошо, но на РК мы проверяем реальную базу в том числе

**Comment by StealthTech** [comment]
![image](https://github.com/frontend-park-mail-ru/2023_2_Rabotyagi/assets/5190765/653c6496-0511-4259-ae2b-7420824cac1a)
Часть картинок не работает

![image](https://github.com/frontend-park-mail-ru/2023_2_Rabotyagi/assets/5190765/222f82ee-fb9a-47c4-b549-a13df88acbda)
![image](https://github.com/frontend-park-mail-ru/2023_2_Rabotyagi/assets/5190765/ca9b664b-46b7-4de1-ad94-e5f06c2d3239)
На входе сломана верстка

Почистите от неиспользуемых зависимостей package.json

**Comment by GreatFix** [comment]
@StealthTech привет, глянешь еще? Ребята хотя уже к защите следующих рк приступить

**Comment by StealthTech** [comment]
Пересдача засчитана, баллы в ведомости
