### ISSUE TITLE
Добавь простую отрисовку постов, чтобы их было видно в верстке, а не в консоли

### ISSUE THREAD

**Issue by GreatFix** [frontend-park-mail-ru/2023_2_Rabotyagi#2]
https://github.com/frontend-park-mail-ru/2023_2_Rabotyagi/blob/36222b64409c687ebb4b5b0973fc355534ca3229/public/components/posts/feed.mjs#L16

**Comment by NickDemiman** [comment]
это есть, просто в dev лежит, а не в мастере
