### ISSUE TITLE
Поправить сборку и подключение стилей

### ISSUE THREAD

**Issue by GreatFix** [frontend-park-mail-ru/2023_2_Rabotyagi#25]
Сделать для css отдельный rule без sass loader

https://github.com/frontend-park-mail-ru/2023_2_Rabotyagi/blob/f534e47d4949d37e9e176c1f7af2e91d581ed49d/webpack.config.js#L52C8-L52C8

Подключить плагин mini-css-extract-plugin , чтобы стили собирались в один файл (еще можно для каждого компонента отдельный файл, но это посложней и нет смысла тратить на это время)

В итоге после билда будет создавать файл, типа main.css, вот его подключить тут https://github.com/frontend-park-mail-ru/2023_2_Rabotyagi/blob/f534e47d4949d37e9e176c1f7af2e91d581ed49d/public/index.html#L5

public/css/font.css и public/css/reset.css перенести в src/assets/css и подключить также, как и остальные. (reset должен быть первым, если что). шрифты тоже в папку src/assets (но если сможете подключить через абсолютный путь, можете оставить в паблик, я быстро чекнул, не получилось).

во всех js файлах подключать стиле в формате ` import "./{filename}.(css|scss)"`

Убрать везде подключение вроде 
`
 import css from "./{filename}.(css|scss)"
 element.style = css;
`

**Comment by GreatFix** [comment]
Также стоит переименовать папку с билдом, т.к. туда не только дж попадает. Обычно называют dist или build

https://github.com/frontend-park-mail-ru/2023_2_Rabotyagi/blob/f534e47d4949d37e9e176c1f7af2e91d581ed49d/webpack.config.js#L13

**Comment by NickDemiman** [comment]
Все переименовал и перенес, но проблема со шрифтами осталась

**Comment by GreatFix** [comment]
Ну судя по всему, проблема в ttf, кажется он для сафари и мобилок. Попробуй woff шрифты тоже подключить. Надо будет вебпак конфиг также как тут поправить https://webpack.js.org/guides/asset-management/#loading-fonts

**Comment by NickDemiman** [comment]
по идее можно закрывать, ведь вроде все поправлено
/cc @GreatFix

**Comment by GreatFix** [comment]
Пока не смержено в мастер, не поправлено

**Comment by NickDemiman** [comment]
а сейчас можно закрывать?

**Comment by GreatFix** [comment]
Угу, давай закрывай)
