### ISSUE TITLE
Переработать структуру папок

### ISSUE THREAD

**Issue by GreatFix** [frontend-park-mail-ru/2023_2_Rabotyagi#4]
Сейчас все находится в папке public.

Обычно принято там располагать только статику/html/ images и т.д.

Давай приведем к виду
```
public/
  assets/
    images/
    icons/
  index.html 
src/
  components/ (одна папка под один компонент. Можно еще подпапки добавить)
  shared/
    services/ (здесь api сервисы)
    utils/ (вспомогательные функции)
    constants/
  pages/  (один js файл на одну страницу и только один файл routes.js, в котором мапятся роуты с страницами)
  index.js ( Здесь инициализируется приложения)
index.ts (здесь инициализируется express)
```

Не обязательно делать именно такую структуру, ключевое здесь именно разделение public и src, а также отделение ui от логики (насколько это возможно)

**Comment by NickDemiman** [comment]
Переработал, чуть позже создам МР. Помечаю для себя просто
