### ISSUE TITLE
Добавить npm script

### ISSUE THREAD

**Issue by GreatFix** [frontend-park-mail-ru/2023_2_Rabotyagi#6]
https://github.com/frontend-park-mail-ru/2023_2_Rabotyagi/blob/7f1b2a6b44c91d16f6908b272a2f6c74298ed429/package.json#L7

Чтобы не писать каждый раз node server/server.js, стоит добавить здесь быструю команду

**Comment by NickDemiman** [comment]
Уже лежит в мастере
